services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - begriff_network

  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./src/domains/risk/models:/app/src/domains/risk/models
      
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - gateway_server
      - open_banking_mock_server
      - blockchain_node
    networks:
      - begriff_network

  gateway_server:
    build:
      context: . # O contexto agora é a raiz do projeto
      dockerfile: ./src/infra/gateways/performance_gateway/Dockerfile # Caminho completo para o Dockerfile
    ports:
      - "8081:8081"
    networks:
      - begriff_network

  open_banking_mock_server:
    build:
      context: ./src/infra/mocks/open_banking_provider
    ports:
      - "8080:8080"
    networks:
      - begriff_network

  blockchain_node:
    build:
      context: ./src/infra/blockchain/node
    working_dir: /app
    ports:
      - "8545:8545"
    networks:
      - begriff_network

networks:
  begriff_network:
    driver: bridge

volumes:
  postgres_data: